'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {

     await queryInterface.bulkInsert('Staffs', [{
       name: 'Готман Юрий Альфредович',
       img: 'gotman.png',
       categorie: 'Руководство',
       position: 'Генеральный директор',
       description: 'Hero',
       about: 'superman',
       about1: 'superman1',
       about2: 'superman2',
       about3: 'superman3',
       about4: 'superman4',
       about5: 'superman5',
       createdAt: new Date(),
       updatedAt: new Date(),
     },
     {
      name: 'Магзумов Раиль Наилович',
      img: 'magzumov.png',
      categorie: 'Руководство',
      position: 'Первый заместитель',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Колесников Роман Игоревич',
      img: 'kolesnikov.png',
      categorie: 'Руководство',
      position: 'Заместитель генерального директора',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Бикбулатов Мансур Иршатович',
      img: 'bikbulatov.png',
      categorie: 'Руководство',
      position: 'Заместитель генерального директора по общим вопросам',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Илютенко Денис Владимирович',
      img: 'ilutenko.png',
      categorie: 'Руководство',
      position: 'Заместитель генерального директора по проектированию',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Васильев Максим Львович',
      img: 'vasilev.png',
      categorie: 'Руководство',
      position: 'Заместитель генерального директора по объектам метрополитена транспортной инфраструктуры',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Галяутдинов Рустам Салаватович',
      img: 'galayutdinov.png',
      categorie: 'Руководство',
      position: 'Заместитель генерального директора по объектам промышленного назначения',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      createdAt: new Date(),
      updatedAt: new Date(),
     },
    {
     name: 'Котов Алексей Игоревич',
     img: 'kotov.png',
     categorie: 'Руководство',
     position: 'Заместитель генерального директора по объектам благоустройства',
     description: 'Hero',
     about: 'superman',
     about1: 'superman1',
     about2: 'superman2',
     about3: 'superman3',
     about4: 'superman4',
     about5: 'superman5',
     createdAt: new Date(),
     updatedAt: new Date(),
    },], {});
  },

  async down (queryInterface, Sequelize) {
  
     await queryInterface.bulkDelete('Staffs', null, {});
 
  }
};
