'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {

     await queryInterface.bulkInsert('Staffs', [{
       name: 'Готман Юрий Альфредович',
       img: 'gotman.png',
       category: 'Руководство',
       position: 'Генеральный директор',
       description: 'Генеральный директор группы компаний MARKS. Кандидат технических наук.  Автор более 15 научных публикаций.',
       about: 'Более 17 лет в проектировании и науке:',
       about1: 'оснований фундаментов, ограждений, конструкций и подземных сооружений, техническое обследование фундаментов и строительных конструкций;',
       about2: 'мониторинг состояния зданий и сооружений;',
       about3: 'проведение исследований в области механики грунтов, геомеханики подземных сооружений и фундаментостроения, разработка регламентов по безопасности эксплуатации зданий и сооружений, комплексного проектирования жилых и многофункциональных зданий в г. Москве и на территории России.',
       about4: 'оснований фундаментов, ограждений, конструкций и подземных сооружений, техническое обследование фундаментов и строительных конструкций;',
       about5: 'мониторинг состояния зданий и сооружений; проведение исследований в области механики грунтов, геомеханики подземных сооружений и фундаментостроения, разработка регламентов по безопасности эксплуатации зданий и сооружений, комплексного проектирования жилых и многофункциональных зданий в г. Москве и на территории России.',
      //  userId: "1",
       createdAt: new Date(),
       updatedAt: new Date(),
     },
     {
      name: 'Магзумов Раиль Наилович',
      img: 'magzumov.png',
      category: 'Руководство',
      position: 'Первый заместитель',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      // userId: "2",
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Колесников Роман Игоревич',
      img: 'kolesnikov.png',
      category: 'Руководство',
      position: 'Заместитель генерального директора',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      // userId: "3",
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Бикбулатов Мансур Иршатович',
      img: 'bikbulatov.png',
      category: 'Руководство',
      position: 'Заместитель генерального директора по общим вопросам',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      // userId: "4",
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Илютенко Денис Владимирович',
      img: 'ilutenko.png',
      category: 'Руководство',
      position: 'Заместитель генерального директора по проектированию',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      // userId: "5",
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Васильев Максим Львович',
      img: 'vasilev.png',
      category: 'Руководство',
      position: 'Заместитель генерального директора по объектам метрополитена транспортной инфраструктуры',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      // userId: "6",
      createdAt: new Date(),
      updatedAt: new Date(),
     },
     {
      name: 'Галяутдинов Рустам Салаватович',
      img: 'galayutdinov.png',
      category: 'Руководство',
      position: 'Заместитель генерального директора по объектам промышленного назначения',
      description: 'Hero',
      about: 'superman',
      about1: 'superman1',
      about2: 'superman2',
      about3: 'superman3',
      about4: 'superman4',
      about5: 'superman5',
      // userId: "7",
      createdAt: new Date(),
      updatedAt: new Date(),
     },
    {
     name: 'Котов Алексей Игоревич',
     img: 'kotov.png',
     category: 'Руководство',
     position: 'Заместитель генерального директора по объектам благоустройства',
     description: 'Hero',
     about: 'superman',
     about1: 'superman1',
     about2: 'superman2',
     about3: 'superman3',
     about4: 'superman4',
     about5: 'superman5',
    //  userId: "8",
     createdAt: new Date(),
     updatedAt: new Date(),
    },], {});
  },

  async down (queryInterface, Sequelize) {
  
     await queryInterface.bulkDelete('Staffs', null, {});
 
  }
};
